// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabasecontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Background.CarInHighway", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int?>("DriverID")
                        .HasColumnType("int");

                    b.Property<int>("HighwayId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastLocationChangeTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("Location")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CarId")
                        .IsUnique();

                    b.HasIndex("DriverID");

                    b.HasIndex("HighwayId");

                    b.ToTable("CarsInHighWay");
                });

            modelBuilder.Entity("Entities.Background.Highway", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HighWayDirection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MaxAllowedSpeed")
                        .HasColumnType("float");

                    b.Property<string>("Wheather")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Highways");
                });

            modelBuilder.Entity("Entities.Background.SpeedCamera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HighWayId")
                        .HasColumnType("int");

                    b.Property<double>("Location")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("HighWayId");

                    b.ToTable("SpeedCameras");
                });

            modelBuilder.Entity("Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("PlateNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("carsListId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("carsListId");

                    b.ToTable("cars");
                });

            modelBuilder.Entity("Entities.CarsList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CarLength")
                        .HasColumnType("float");

                    b.Property<double>("MaxSpeed")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CarsLists");
                });

            modelBuilder.Entity("Entities.Highway.DetectedCarBySpeedCam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DetectTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DetectedCarId")
                        .HasColumnType("int");

                    b.Property<int?>("SpeedCameraId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DetectedCarId");

                    b.HasIndex("SpeedCameraId");

                    b.ToTable("DetectedCarsBySpeedCam");
                });

            modelBuilder.Entity("Entities.Highway.Driver", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Speed")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("persons");
                });

            modelBuilder.Entity("Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TicketDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TicketsListId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("TicketsListId");

                    b.ToTable("tickets");
                });

            modelBuilder.Entity("Entities.TicketsList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("ticketsList");
                });

            modelBuilder.Entity("Entities.Background.CarInHighway", b =>
                {
                    b.HasOne("Entities.Car", "Car")
                        .WithOne("CarInHighway")
                        .HasForeignKey("Entities.Background.CarInHighway", "CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Highway.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverID");

                    b.HasOne("Entities.Background.Highway", "Highway")
                        .WithMany("CarInHighWays")
                        .HasForeignKey("HighwayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Driver");

                    b.Navigation("Highway");
                });

            modelBuilder.Entity("Entities.Background.SpeedCamera", b =>
                {
                    b.HasOne("Entities.Background.Highway", "Highway")
                        .WithMany("SpeedCameras")
                        .HasForeignKey("HighWayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Highway");
                });

            modelBuilder.Entity("Entities.Car", b =>
                {
                    b.HasOne("Entities.Person", "Owner")
                        .WithMany("Cars")
                        .HasForeignKey("OwnerId");

                    b.HasOne("Entities.CarsList", "carsList")
                        .WithMany("Cars")
                        .HasForeignKey("carsListId");

                    b.Navigation("carsList");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Entities.Highway.DetectedCarBySpeedCam", b =>
                {
                    b.HasOne("Entities.Car", "DetectedCar")
                        .WithMany()
                        .HasForeignKey("DetectedCarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Background.SpeedCamera", "SpeedCamera")
                        .WithMany("DetectedCars")
                        .HasForeignKey("SpeedCameraId");

                    b.Navigation("DetectedCar");

                    b.Navigation("SpeedCamera");
                });

            modelBuilder.Entity("Entities.Ticket", b =>
                {
                    b.HasOne("Entities.Car", "Car")
                        .WithMany("Tickets")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.TicketsList", "TicketsList")
                        .WithMany("Tickets")
                        .HasForeignKey("TicketsListId");

                    b.Navigation("Car");

                    b.Navigation("TicketsList");
                });

            modelBuilder.Entity("Entities.Background.Highway", b =>
                {
                    b.Navigation("CarInHighWays");

                    b.Navigation("SpeedCameras");
                });

            modelBuilder.Entity("Entities.Background.SpeedCamera", b =>
                {
                    b.Navigation("DetectedCars");
                });

            modelBuilder.Entity("Entities.Car", b =>
                {
                    b.Navigation("CarInHighway");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Entities.CarsList", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("Entities.TicketsList", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
